#' Compile R functions
#'
#' Generates TypeScript schema for the given R function or file path. If a path, the R app is also generated.
#'
#' @param f A function or file path
#' @param name The name of the function
#' @param ... Additional arguments (passed to ts_deploy)
#' @param filename The base file path to write the TypeScript schema and R app to (optional, uses `[path of f].rserve` by default). `.R` and `.ts` file extensions are appended automatically. If `""`, the output is printed to the standard output console (see `cat`).
#' @return Character vector of TypeScript schema, or NULL if writing to file
#' @md
#' @export
ts_compile <- function(f, ..., name, filename) {
    o <- UseMethod("ts_compile")
}

compile_fn <- function(f) {
    inputs <- f$args
    result <- f$result

    inputs <- sapply(inputs, \(x) x$input_type)
    fn_args <- paste(paste(inputs), collapse = ", ")
    # Use get_type dispatch so ts_function/ts_widget results compile correctly
    # (e.g., a method returning a widget connector produces nested Robj.ocap)
    ret_type <- get_type(result, "return")
    sprintf(
        "Robj.ocap([%s], %s)",
        fn_args,
        ret_type
    )
}

#' @export
ts_compile.ts_function <- function(f, ..., name = deparse(substitute(f))) {
    ocap_str <- compile_fn(f)

    sprintf(
        "export const %s = %s;", name, ocap_str
    )
}

#' @export
ts_compile.character <- function(
    f,
    ...,
    filename = sprintf("%s.rserve", tools::file_path_sans_ext(f))) {
    if (length(f) > 1) {
        return(sapply(f, ts_compile))
    }

    if (!file.exists(f)) {
        warning(sprintf("File not found: %s", f))
        return()
    }
    # Track what exists before sourcing so we can find new definitions
    pre_globals <- ls(globalenv())
    e <- new.env(parent = globalenv())
    source(f, local = e)

    # Collect exports from both the local env and any new globals
    # (inner source() calls default to local=FALSE, putting defs in globalenv)
    new_globals <- setdiff(ls(globalenv()), pre_globals)
    candidates <- unique(c(ls(e), new_globals))
    # Look up each candidate from e first, then globalenv
    lookup <- function(name) {
        if (exists(name, envir = e, inherits = FALSE)) e[[name]]
        else if (exists(name, envir = globalenv(), inherits = FALSE)) get(name, envir = globalenv())
        else NULL
    }
    is_exported <- sapply(candidates, \(z) {
        obj <- lookup(z)
        inherits(obj, "ts_function") && isTRUE(obj$export)
    })
    exports <- candidates[is_exported]

    # Separate top-level app exports from child-only widget definitions.
    # A widget is "child-only" if its definition object is used as a child
    # property of another exported widget, or as the return type of a method.
    child_defs <- list()
    for (z in exports) {
        obj <- lookup(z)
        if (inherits(obj, "ts_widget")) {
            wp <- attr(obj, ".__props")$widgets
            child_defs <- c(child_defs, unname(wp))
            # Also check method return types for widget references
            method_defs <- attr(obj, ".__methods")$exported_defs
            for (m in method_defs) {
                if (inherits(m$result, "ts_widget")) {
                    child_defs <- c(child_defs, list(m$result))
                }
            }
        }
    }
    is_child_only <- sapply(exports, \(z) {
        obj <- lookup(z)
        any(vapply(child_defs, identical, logical(1), obj))
    })
    app_exports <- exports[!is_child_only]
    widget_exports <- exports[is_child_only]

    exportFns <- sapply(
        exports,
        \(z) ts_compile(lookup(z), filename = "", name = z)
    )

    # Generate type aliases for each export
    # Capitalize first letter: iNZDocument -> TINZDocument
    capitalize_first <- function(x) paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))
    type_aliases <- sapply(
        exports,
        \(z) sprintf("export type T%s = z.infer<typeof %s>;", capitalize_first(z), z)
    )

    src <- c(
        "// This file is auto-generated by ts_compile() - do not edit manually.",
        sprintf("// Source: %s", f),
        "",
        "import { Robj } from 'rserve-ts';",
        "import { z } from 'zod';",
        "\n",
        exportFns,
        "\n",
        type_aliases,
        "\n",
        sprintf(
            "export default {\n  %s\n};",
            paste(app_exports, collapse = ",\n  ")
        )
    )

    cat(src, file = sprintf("%s.ts", filename), sep = "\n")

    # R file
    ts_deploy(f, file = sprintf("%s.R", filename), silent = TRUE, ...)

    invisible()
}

#' @export
ts_compile.default <- function(f, ...) {
    warning("Not supported")
}
