# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push, pull_request]
name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12

      # the rest of this must run from tests/testthat/sampler
      - run: pnpm install --frozen-lockfile
        working-directory: tests/testthat/sampler

      - run: pnpm build
        working-directory: tests/testthat/sampler

      - run: pnpm start
        working-directory: tests/testthat/sampler
